### ISSUE TITLE
Support for yaml and environment variables

### ISSUE THREAD

**Issue by adyanth** [r7wx/easy-gate#11]
YAML should be very straightforward since Go has native support. Environment variables would help a lot in containerised deployments.

**Comment by r7wx** [comment]
Hello, I do not think that moving from json to yaml at this time is worth it, since the main advantage would be personal preference. Also keeping both format could increase confusion on configuration guidelines.

As for environment variables could you provide some example of what you suggest? As I am picturing it now it would become really annoying to set up a large list of services through environment variables.

**Comment by r7wx** [comment]
Personally I prefer to read/write JSON file manually other than YAML, I think I should probably take the Voight-Kampff test :D
However I I have thought about it and I will introduce both configuration file format in the next release.
As for environment variables, since I am not familiar with kubernetes yet, I am not sure if you intend to provide the configuration file path as variable or the entire configuration (I will install a test instance and read more about ConfigMaps).

**Comment by r7wx** [comment]
New release out:

* Configuration file can now be in YAML format.
* Configuration file path can now be overwritten with the EASY_GATE_CONFIG_PATH env variable.
* Configuration file content can now be overwritten with the EASY_GATE_CONFIG env variable.
